import React, { useState, useEffect } from 'react';
import { BrainCircuit, Database, Cpu, ShieldAlert, FileText, Terminal, Settings } from 'lucide-react';

export default function AiArchitecture({ token: propToken }) {
  const inputs = [
    { name: 'Security Logs', desc: 'Raw system logs (SSH auth tries, firewall blocked events, web traversal directories access).' },
    { name: 'Transaction Events', desc: 'Real-time financial transactions details (UPI requests, payout payloads, merchant transfers).' },
    { name: 'User Activity Logs', desc: 'Attribution telemetry mapping session geolocation shifts and browser user-agent tokens.' },
    { name: 'Threat Intelligence', desc: 'TAXII/STIX lists updating malicious IP reputations and fraudulent credit card BIN metrics.' }
  ];

  const engine = [
    { name: 'Pattern Matching', desc: 'Stateful clustering rules isolating geographical anomalies and checkout device shifts.' },
    { name: 'Risk Scoring', desc: 'Deterministic weights calculations tracking payments failure frequencies and targeted host values.' },
    { name: 'Event Aggregation', desc: 'Consolidates 100+ separate syslog entries into distinct actor clusters over time.' }
  ];

  const pipeline = [
    { agent: '1. Parser Agent', strategy: 'Regex cleaning normalizations', purpose: 'Maps logs schemas to database targets.' },
    { agent: '2. Correlation Agent', strategy: 'Time-window grouping blocks', purpose: 'Calculates base statistics & anomalies.' },
    { agent: '3. Detection Agent', strategy: 'MITRE ATT&CK rules matching', purpose: 'Flags incidents based on scores thresholds.' },
    { agent: '4. Investigation Agent', strategy: 'Gemini flash generative prompting', purpose: 'Drafts forensic summaries & root causes.' },
    { agent: '5. Response Agent', strategy: 'Playbook catalog mapping', purpose: 'Synthesizes containment operations commands.' },
    { agent: '6. Report Agent', strategy: 'Markdown report compiler', purpose: 'Compiles technical and compliance briefs.' }
  ];

  const outputs = [
    { name: 'Incident Ticket', desc: 'Correlated INC-xxxx ticket detailing status, category, and base risk factors.' },
    { name: 'Chronological Timeline', desc: 'Visual trace timeline detailing raw event logs up to remediation block steps.' },
    { name: 'Response Playbook', desc: 'Click-to-run playbook containment rules (e.g., block IP, reset tokens).' },
    { name: 'Executive Report', desc: 'Markdown technical brief generated by report agents for compliance records.' }
  ];

  const [activeStep, setActiveStep] = useState(1);
  const [stats, setStats] = useState({ aiModel: 'gemini-3.6-flash', agentExecutions: 0, avgLatency: '1.2s' });

  useEffect(() => {
    const fetchStats = async () => {
      try {
        const token = propToken || localStorage.getItem('soc_token');
        if (!token) return;
        const res = await fetch('/api/stats', { headers: { 'Authorization': `Bearer ${token}` }});
        if (res.ok) {
          const data = await res.json();
          setStats(data);
        }
      } catch (err) {
        console.error(err);
      }
    };
    fetchStats();
    const statsTimer = setInterval(fetchStats, 5000);

    const timer = setInterval(() => {
      setActiveStep(prev => (prev >= 8 ? 1 : prev + 1));
    }, 1500);
    
    return () => {
      clearInterval(timer);
      clearInterval(statsTimer);
    };
  }, []);

  return (
    <div className="space-y-6 text-left font-sans text-xs select-none">
      
      {/* Header section */}
      <div className="flex flex-col md:flex-row md:items-end justify-between border-b border-[#2A3A52] pb-3">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-white flex items-center">
            <BrainCircuit className="w-5 h-5 mr-2 text-[#38BDF8]" /> MULTI_AGENT_AI_ARCHITECTURE
          </h1>
          <p className="text-xs text-[#9CA3AF] mt-0.5">Interviewer-facing specification sheet mapping inputs, correlation rules, and pipeline outputs.</p>
        </div>
        
        <div className="flex items-center space-x-4 mt-3 md:mt-0 bg-[#111827] border border-[#2A3A52] p-2 rounded">
          <div className="flex flex-col px-2 border-r border-[#2A3A52]">
            <span className="text-[8px] text-[#9CA3AF] uppercase font-bold">AI Model</span>
            <span className="text-white font-mono">{stats.aiModel}</span>
          </div>
          <div className="flex flex-col px-2 border-r border-[#2A3A52]">
            <span className="text-[8px] text-[#9CA3AF] uppercase font-bold">Agent Executions</span>
            <span className="text-[#38BDF8] font-bold font-mono">{stats.agentExecutions}</span>
          </div>
          <div className="flex flex-col px-2">
            <span className="text-[8px] text-[#9CA3AF] uppercase font-bold">Avg Latency</span>
            <span className="text-[#10B981] font-bold font-mono">{stats.avgLatency}</span>
          </div>
        </div>
      </div>

      {/* Visual Sequence Flowchart Diagram */}
      <div className="bg-[#131C2E] border border-[#2A3A52] p-5 rounded-lg space-y-4">
        <h3 className="text-xs font-bold text-white uppercase tracking-wider font-sans border-b border-[#2A3A52] pb-2">
          Unified Agent Telemetry Processing Pipeline
        </h3>
        
        <div className="overflow-x-auto py-2">
          <div className="min-w-[850px] flex items-center justify-between text-center font-mono text-[9px] select-none text-white">
            
            <div className={`border p-2.5 rounded w-24 transition duration-300 ${activeStep === 1 ? 'bg-[#38BDF8]/20 border-[#38BDF8] scale-105 shadow-[0_0_15px_rgba(56,189,248,0.5)]' : 'bg-[#0B1220] border-[#2A3A52]'}`}>
              <span className={`block font-bold ${activeStep === 1 ? 'text-[#38BDF8]' : 'text-[#9CA3AF]'}`}>1. INPUTS</span>
              <span className="text-[8px] text-slate-500 block mt-1">Raw Syslogs / CSV</span>
            </div>
            
            <div className={`font-bold transition ${activeStep === 1 ? 'text-[#38BDF8]' : 'text-[#2A3A52]'}`}>→</div>

            <div className={`border p-2.5 rounded w-24 transition duration-300 ${activeStep === 2 ? 'bg-[#38BDF8]/20 border-[#38BDF8] scale-105 shadow-[0_0_15px_rgba(56,189,248,0.5)]' : 'bg-[#0B1220] border-[#2A3A52]'}`}>
              <span className={`block font-bold ${activeStep === 2 ? 'text-white' : 'text-[#38BDF8]'}`}>2. PARSER</span>
              <span className="text-[8px] text-slate-500 block mt-1">Regex Normalization</span>
            </div>

            <div className={`font-bold transition ${activeStep === 2 ? 'text-[#F59E0B]' : 'text-[#2A3A52]'}`}>→</div>

            <div className={`border p-2.5 rounded w-24 transition duration-300 ${activeStep === 3 ? 'bg-[#F59E0B]/20 border-[#F59E0B] scale-105 shadow-[0_0_15px_rgba(245,158,11,0.5)]' : 'bg-[#0B1220] border-[#2A3A52]'}`}>
              <span className={`block font-bold ${activeStep === 3 ? 'text-white' : 'text-[#F59E0B]'}`}>3. CORRELATION</span>
              <span className="text-[8px] text-slate-500 block mt-1">Clustering Engine</span>
            </div>

            <div className={`font-bold transition ${activeStep === 3 ? 'text-[#EF4444]' : 'text-[#2A3A52]'}`}>→</div>

            <div className={`border p-2.5 rounded w-28 transition duration-300 ${activeStep === 4 ? 'bg-[#EF4444]/20 border-[#EF4444] scale-105 shadow-[0_0_15px_rgba(239,68,68,0.5)]' : 'bg-[#0B1220] border-[#2A3A52]'}`}>
              <span className={`block font-bold ${activeStep === 4 ? 'text-white' : 'text-[#EF4444]'}`}>4. DETECTION</span>
              <span className="text-[8px] text-slate-500 block mt-1">MITRE Rule Match</span>
            </div>

            <div className={`font-bold transition ${activeStep === 4 ? 'text-[#22C55E]' : 'text-[#2A3A52]'}`}>→</div>

            <div className={`border p-2.5 rounded w-28 transition duration-300 ${activeStep === 5 ? 'bg-[#22C55E]/20 border-[#22C55E] scale-105 shadow-[0_0_15px_rgba(34,197,94,0.5)]' : 'bg-[#0B1220] border-[#2A3A52]'}`}>
              <span className={`block font-bold ${activeStep === 5 ? 'text-white' : 'text-[#22C55E]'}`}>5. INVESTIGATE</span>
              <span className="text-[8px] text-slate-500 block mt-1">Gemini flash LLM</span>
            </div>

            <div className={`font-bold transition ${activeStep === 5 ? 'text-[#A855F7]' : 'text-[#2A3A52]'}`}>→</div>

            <div className={`border p-2.5 rounded w-24 transition duration-300 ${activeStep === 6 ? 'bg-[#A855F7]/20 border-[#A855F7] scale-105 shadow-[0_0_15px_rgba(168,85,247,0.5)]' : 'bg-[#0B1220] border-[#2A3A52]'}`}>
              <span className={`block font-bold ${activeStep === 6 ? 'text-white' : 'text-[#A855F7]'}`}>6. RESPONSE</span>
              <span className="text-[8px] text-slate-500 block mt-1">Quarantine Actions</span>
            </div>

            <div className={`font-bold transition ${activeStep === 6 ? 'text-[#38BDF8]' : 'text-[#2A3A52]'}`}>→</div>

            <div className={`border p-2.5 rounded w-24 transition duration-300 ${activeStep === 7 ? 'bg-[#38BDF8]/20 border-[#38BDF8] scale-105 shadow-[0_0_15px_rgba(56,189,248,0.5)]' : 'bg-[#0B1220] border-[#2A3A52]'}`}>
              <span className={`block font-bold ${activeStep === 7 ? 'text-white' : 'text-[#38BDF8]'}`}>7. REPORTING</span>
              <span className="text-[8px] text-slate-500 block mt-1">Compliance Markdown</span>
            </div>

            <div className={`font-bold transition ${activeStep === 7 ? 'text-[#10B981]' : 'text-[#2A3A52]'}`}>→</div>

            <div className={`border p-2.5 rounded w-24 transition duration-300 ${activeStep === 8 ? 'bg-[#10B981]/20 border-[#10B981] scale-105 shadow-[0_0_15px_rgba(16,185,129,0.5)]' : 'bg-[#0B1220] border-[#2A3A52]'}`}>
              <span className={`block font-bold ${activeStep === 8 ? 'text-white' : 'text-[#10B981]'}`}>8. OUTPUTS</span>
              <span className="text-[8px] text-slate-500 block mt-1">Incident Tickets</span>
            </div>

          </div>
        </div>
      </div>

      {/* Grid: 4-Pillars Core Architecture */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        
        {/* Section 1: System Inputs */}
        <div className="bg-[#131C2E] border border-[#2A3A52] p-4 rounded-lg space-y-3">
          <div className="border-b border-[#2A3A52] pb-1.5 flex items-center space-x-2">
            <Database className="w-4 h-4 text-[#38BDF8]" />
            <h3 className="font-bold text-white uppercase text-[10px]">1. Ingestion System Inputs</h3>
          </div>
          <div className="space-y-2">
            {inputs.map((item, idx) => (
              <div key={idx} className="bg-[#0B1220] border border-[#2A3A52] p-2.5 rounded hover:border-[#38BDF8]/20 transition">
                <span className="font-bold text-[#E5E7EB] block mb-0.5">{item.name}</span>
                <span className="text-[#9CA3AF] leading-relaxed block">{item.desc}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Section 2: Correlation Engine */}
        <div className="bg-[#131C2E] border border-[#2A3A52] p-4 rounded-lg space-y-3">
          <div className="border-b border-[#2A3A52] pb-1.5 flex items-center space-x-2">
            <Cpu className="w-4 h-4 text-[#F59E0B]" />
            <h3 className="font-bold text-white uppercase text-[10px]">2. Correlation Engine Parameters</h3>
          </div>
          <div className="space-y-2">
            {engine.map((item, idx) => (
              <div key={idx} className="bg-[#0B1220] border border-[#2A3A52] p-2.5 rounded hover:border-[#F59E0B]/20 transition">
                <span className="font-bold text-[#E5E7EB] block mb-0.5">{item.name}</span>
                <span className="text-[#9CA3AF] leading-relaxed block">{item.desc}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Section 3: Agent Pipeline */}
        <div className="bg-[#131C2E] border border-[#2A3A52] p-4 rounded-lg space-y-3 lg:col-span-2">
          <div className="border-b border-[#2A3A52] pb-1.5 flex items-center space-x-2">
            <BrainCircuit className="w-4 h-4 text-[#22C55E]" />
            <h3 className="font-bold text-white uppercase text-[10px]">3. Autonomic Agent Pipeline Sequence</h3>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            {pipeline.map((item, idx) => (
              <div key={idx} className="bg-[#0B1220] border border-[#2A3A52] p-3 rounded flex flex-col justify-between hover:border-[#22C55E]/20 transition">
                <div className="space-y-1">
                  <span className="font-bold text-white block text-[10px]">{item.agent}</span>
                  <span className="text-[9px] text-[#38BDF8] block font-mono">[{item.strategy}]</span>
                </div>
                <span className="text-[#9CA3AF] mt-2 block leading-relaxed">{item.purpose}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Section 4: Outputs */}
        <div className="bg-[#131C2E] border border-[#2A3A52] p-4 rounded-lg space-y-3 lg:col-span-2">
          <div className="border-b border-[#2A3A52] pb-1.5 flex items-center space-x-2">
            <FileText className="w-4 h-4 text-[#EF4444]" />
            <h3 className="font-bold text-white uppercase text-[10px]">4. Platform Output Yields</h3>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
            {outputs.map((item, idx) => (
              <div key={idx} className="bg-[#0B1220] border border-[#2A3A52] p-3 rounded hover:border-[#EF4444]/20 transition">
                <span className="font-bold text-[#E5E7EB] block mb-0.5 font-sans">{item.name}</span>
                <span className="text-[#9CA3AF] leading-relaxed block">{item.desc}</span>
              </div>
            ))}
          </div>
        </div>

      </div>

    </div>
  );
}
